name: Trigger Rebase

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.repository == 'mhalbritter/automatic-rebase-source'
    steps:
      - name: Trigger workflow in automatic-rebase-target
        env:
          GH_TOKEN: ${{ secrets.REBASE_TARGET_TOKEN }}
        run: |
          gh workflow run --repo mhalbritter/automatic-rebase-target rebase.yml
